### ISSUE TITLE
Security groups configuration cannot be read by Senza

### ISSUE THREAD

**Issue by ehartung** [zalando/saiki-kewan#5]
Hi, 

when trying to deploy kewan to AWS with Senza I'm getting the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/senza", line 9, in <module>
    load_entry_point('stups-senza==0.53', 'console_scripts', 'senza')()
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 798, in main
    handle_exceptions(cli)()
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 219, in wrapper
    func()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 368, in create
    data = evaluate(input.copy(), args, force)
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 205, in evaluate
    definition = componentfn(definition, configuration, args, info, force)
  File "/usr/local/lib/python3.4/dist-packages/senza/components.py", line 407, in component_taupage_auto_scaling_group
    definition = component_auto_scaling_group(definition, configuration, args, info, force)
  File "/usr/local/lib/python3.4/dist-packages/senza/components.py", line 276, in component_auto_scaling_group
    resolve_security_groups(configuration["SecurityGroups"], args.region)
  File "/usr/local/lib/python3.4/dist-packages/senza/components.py", line 580, in resolve_security_groups
    if id_or_name.startswith('sg-'):
AttributeError: 'dict' object has no attribute 'startswith'
```
Do I have to prepare security groups in advance?

Cheers.

**Comment by drummerwolli** [comment]
we're using some newer features of senza, which include creating security groups as described in the yaml file. see here for ref:

https://github.com/zalando-stups/senza/issues/63
https://github.com/zalando-stups/senza/pull/64

have you upgraded to the latest senza version?
```pip3 install --upgrade stups```

**Comment by ehartung** [comment]
yes, I upgraded the Stups tools, though the Senza version is only 0.53. Which version is needed?

**Comment by drummerwolli** [comment]
it looks like the commit got implemented in 0.60:
https://github.com/zalando-stups/senza/compare/0.59...0.60

**Comment by chutium** [comment]
current senza version should be 0.63, if upgrade stups do not work, probably try
```sudo pip3 install --upgrade stups-senza```

**Comment by ehartung** [comment]
My pip.conf was using an out-dated mirror. After fixing this, I was able to upgrade to Senza 0.63 and deploying works now.

Thx!
